baseURL: "https://sidworks01.github.io/" 
title: Siddhant Gupta
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Blogs
          url: books/
          weight: 5 
        - name: Publications
          url: papers/
          weight: 2
        - name: Projects
          url: courses/
          weight: 3
        - name: About Me
          url: data/
          weight: 4 

params:
    description: "I am Siddhant Gupta , an undergraduate student and an independent researcher working mainly in the field of model interpretibility, Agentic AI and LLMs."
    author: Siddhant Gupta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Siddhant Gupta
          subtitle: "I am Siddhant Gupta, an undergraduate student in Bachelors of Technology (2022-2026) at the Indian Institute of Technology Roorkee (IITR) and an independent researcher collaborating with various open labs and research groups across multiple universities. My primary focus lies in the fields of Model Interpretability, Agentic AI, Multimodal LLMs, and Benchmarking & Evaluations. I thrive on exploring innovative ideas, designing various architectures and frameworks, as well as training models aligned with my research interests. I’m always eager to connect and engage in meaningful discussions with like-minded individuals passionate about AI and solving real world problems."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Projects
              url: courses/
            - name: About Me
              url: data/
            - name: Blogs
              url: books/
            - name: Tags
              url: tags/

    socialIcons:
        - name: Job-market paper
          url: Sid_s_Resume_July2025.pdf
        - name: CV
          url: Sid_Research_July.pdf
        - name: Email
          url: mailto:writetosiddhant@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/siddhant-gupta-95180824b/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=PCh-lf8AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/SidWorks01
        - name: Twitter
          url: https://x.com/SidYaeger
        - name: Discord
          url: https://discord.com/users/minemasterxd
        - name: Hugging Face
          url: https://huggingface.co/minemaster01

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Siddhant Gupta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
